---
title: "Sobol_Example"
author: "Julia Parish"
date: '2022-04-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sensitivity)
library(pse)
library(tidyverse)
library(gridExtra)
library(purrr)
library(ggpubr)
```


Atmospheric Conductance as a function of windspeed, vegetation height and parameters

```{r}
# atmcon function
source("../Labs/R/atmcon.R")
```

```{r}
# generate two examples of random number from parameter distributions
np=1000

k = rnorm(mean=0.1,sd=0.1*0.1, n=np)
kd = rnorm(mean=0.7, sd=0.7*0.1, n=np)
vm = rnorm(mean=200, sd=10, n=np)
h = runif(min=5, max=15, n=np)

X1 = cbind.data.frame(k, kd, vm, h=h)

# repeat sampling
k = rnorm(mean=0.1,sd=0.1*0.1, n=np)
kd = rnorm(mean=0.7, sd=0.7*0.1, n=np)
vm = rnorm(mean=200, sd=10, n=np)
h = runif(min=5, max=15, n=np)

X2 = cbind.data.frame(k, kd, vm, h=h)

# there are different versions of sobol functions that have different approaches for estimating parameters and indices, we use an approach implemented by jansen 
sens_Catm_Sobol = sobolSalt(model = NULL, X1, X2, nboot = 100)
```


```{r}
# Take a look at the Sobol generated sensitivity object
# your parameters sets for sensitivity analysis are in X
# run model for all parameter sets
# make sure you give the parameters names
parms = as.data.frame(sens_Catm_Sobol$X)
colnames(parms) = colnames(X1)

# changed model from list to single result
model_output = pmap_dbl(parms, atmcon) # results

sens_Catm_Sobol = sensitivity::tell(sens_Catm_Sobol, model_output, model_output.names="ga")

# main effect:  partitions variance (main effect without co-variance) - sums approximately to one
sens_Catm_Sobol$S
```

```{r}
# useful to add names - if had to split variance in atmcon, about 73% is associated with height
# tells how variance can be 
row.names(sens_Catm_Sobol$S) = colnames(parms)
sens_Catm_Sobol$S
```

```{r}
# total effect - accounts for parameter interactions
row.names(sens_Catm_Sobol$T) = colnames(parms)
sens_Catm_Sobol$T
```


```{r}
# Both the main effect and total effect can tell us something about how the parameter influences results
print(sens_Catm_Sobol)
```

```{r}
# compare with LHS and PRCC; if this is height, how much of the left over variance in windspeed
sens_Catm$prcc
```


```{r}
# compare with LHS and PRCC; 
# sobol is computationally more complex, longer to calculate, variance based method - better analysis, more modern. 

sens_Catm_Sobol$S
```


```{r}
# compare with LHS and PRCC
sens_Catm_Sobol$T
```


```{r}
# make a data frame for plotting
both = cbind.data.frame(parms, gs=sens_Catm_Sobol$y)
```


```{r}
# look at response of conductance to the two most important variables
ggplot(both, aes(v,gs, col=height))+
  geom_point()+labs(y="Conductance (mm/s)", x="Windspeed")
```